site_name: Touristeer

nav:
  - Início: index.md
  - Visão de Produto e Projeto: 
    - Cenário Atual do Cliente e Negócio: sections/docPage/cenarioAtual.md
    - Solução Proposta: sections/docPage/solucaoProp.md
    - Estratégias de Engenharia de Software: sections/docPage/estrategias.md
    - Cronograma e Entregas: sections/docPage/cronograma.md
    - Interação entre Equipe e Cliente: sections/docPage/interacaoEqCliente.md
    - Lições Aprendidas: sections/docPage/licoesAprendidas.md



theme: 
  name: material
  language: pt-BR

  features:
    - content.code.annotate
      - content.tabs.link
      - header.autohide
      - navigation.instant
      - navigation.top
      - navigation.tracking